name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  versionSemVer: "0.1.0"
  versionSuffixRoot: "ci"
  buildNumber: ${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack /p:PackageVersion=${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}
    - name: Upload
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Itofinity.Bitbucket.Authentication.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.nupkg.zip
        path: ./**/Itofinity.Bitbucket.Authentication*.*.nupkg
    - name: Push
      run: dotnet nuget push ./**/Itofinity.Bitbucket.Authentication*.*.nupkg --api-key ${{ secrets.MYGET_ITOFINITY_APIKEY }} --Source https://www.myget.org/F/itofinity/api/v2/package
